argtable/argtable3

argtable3.c
Otherwise, we get a warning about `warnx()` not being defined.
=> Include "err.h" to be able to use `warnx()`

argtable3.c
Both warnings are false positive, since `opterrmsg` buffer is controled solely by the `warnx` function and `_vsnprintf` appears to be zero-terminating its output as the documentation says. I've changed the `fprintf` call so it guards from a formatting string input to make V618 of the PVS Studio happy, manually zeroed the buffer before `_vsnprintf` call and limited it's output size to (buffer size - 1) to guarantee the output is always zero-terminated despite the implementation and suppressed the warning C6053 of the VS Code Analysis.
=> Fixed format string misuse (V618) and not zero-terminated string (C6053) warnings in win32 'warnx' implementation

conanfile.py, src/argtable3.c, src/argtable3.h
This was fixed at one point in the previous PR I submitted, but it got lost. Now it's back :)
=> Fix `err.h` inclusion to only be used on Linux

CMakeLists.txt, src/CMakeLists.txt, src/arg_cmd.c, src/arg_dbl.c, src/arg_dstr.c, src/arg_file.c, src/arg_hashtable.c, src/arg_int.c, src/arg_rex.c, src/arg_str.c, src/arg_utils.c, src/argtable3.c, src/argtable3.h, src/argtable3_private.h
Is argtable3 really ANSI-C compatible?
I have some projects where there are some stringent `CFLAGS` `'-std=c89 -pedantic'` on them. When including argtable into that project it reported several errors in the library. This patch adds those `CFLAGS` and adjusts the code to make it really ANSI-C compatible.
=> Make argtable3 ANSI-C

src/arg_dstr.c, src/argtable3.c, src/argtable3.h
The arg_dstr_cat() function expects a string. When the function is passed a pointer to char type, the '\0' is missing and produces garbage.
=> Added a new function arg_dstr_catc() for appending char types

src/arg_str.c
arg_parse calls arg_reset to reset data from previous args, but arg_str_resetfn does not clear the string so it causes a parsing issue. 
an example can be found in https://github.com/oopsmonk/iota_esp32_wallet/issues/9
=> Fix the reset function in arg_str

src/argtable3_private.h
They can be a problem for the platforms like NuttX, where
the namespace is flat for everything including apps and libraries.
=> Rename a few generic names to unique names

CMakeLists.txt
Please add `C` to `project` declaration, it enforces cmake to check availability of `c` compiler instead of `c++`.
=> Fixed C compiler detection

src/argtable3.c, src/argtable3.h
Hi @tomghuang, thank you for maintaining this excellent library!
This small PR fixes two issues reported in [esp-idf](https://github.com/espressif/esp-idf) project by clang-tidy:
1. String literals were assigned to `char*` variables instead of `const char*`. The fix looks pretty straightforward.
2. Function argument name in declaration and definition of `arg_end` function was different (`maxerrors` vs `maxcount`). I opted to change the name in the header file for smaller number of changes. Let me know if you prefer it the other way around.
=> Minor clang-tidy fixes

src/argtable3.c
resolves [https://github.com/argtable/argtable3/issues/76](https://github.com/argtable/argtable3/issues/76
)
1. If newline found in text, it is printed and column count is reset.
Previously line wrap would not take newlines found in text into account. Resulting in line wrap feature working incorrectly.
Example:
text: "a b\n c d"
line width: 6
previously:
"a b"
"c"	  <- c in new line because of \n in text
"d"     <- d in new line because column count reached 6 at "c"
and line wrap inserted newline
now:
"a b"
"c d"	<- "c d" in new line because of \n in text,
line wrap does not insert newline between c and d
2. If a very long word is in text, it is broken up differently than before. Previously the long word was printed one character per line. Now as much characters of the long word as can …
=> added two features to arg_print_formatted_ds

src/argtable3.c
see: https://github.com/espressif/esp-idf/pull/10016
=> stack corruption for long cmdline args

src/arg_getopt_long.c, src/argtable3.h, src/argtable3_private.h
This PR aims to improve the flexibility of argtable3 configuration options. With these changes, including argtable3 into other projects becomes easier, since the source code of argtable3 no longer has to be modified. This allows, for example, using the original source files from Github Releases of argtable3, instead of vendoring the argtable3 source code into the project.
* feat: Make ARG_ENABLE_TRACE and ARG_ENABLE_LOG configurable
Currently to configure ARG_ENABLE_TRACE or ARG_ENABLE_LOG, we have to modify argtable3 source code. This commit allows setting these options via the compiler flags.
* feat: make configuration options from argtable3.h configurable
Currently several argtable3 options can be modified only by changing them in source code. This commit makes these options …
=> Improve flexibility of argtable3 configuration options

src/argtable3.c, src/argtable3.h
`arg_print_formatted` was made non-static in 61743612fb, but then was lost in 358498b376f.
This PR makes this function available again.
=> feat: re-introduce `arg_print_formatted`

.clang-tidy, .github/workflows/clang-tidy.yml
Related to https://github.com/argtable/argtable3/issues/70
This PR adds a Github Actions job which:
- runs clang-tidy 
- generates a report in SARIF format, compatible with Github [Code Scanning Alerts](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-alerts).
Clang-tidy is currently run with a minimal set of checks, which produces around 9 warnings in this repository. If we enable all the `bugprone-*` checks, that will be several hundred more, so some cleanup is necessary if we want to enable those. The config is located in `.clang-tidy` file.
The alerts for the existing code will appear at https://github.com/argtable/argtable3/security/code-scanning. That page is visible **only** to repository …
=> ci: run clang-tidy and generate Github code scanning report

src/CMakeLists.txt
Changes CMAKE_CURRENT_SOURCEDIR to CMAKE_CURRENT_SOURCE_DIR.
Fixes #86
=> Update CMakeLists.txt to fix CMAKE_CURRENT_SOURCE_DIR

src/CMakeLists.txt
Hello, I'm one of the maintainers of an homebrew development kit for the Playstation Portable and to be able to build argtable3 for our platform this seems to be the only required change. It would be cool to have this upstream.
=> Make argtable3 able to build for Playstation Portable

src/arg_date.c, src/arg_dbl.c, src/arg_end.c, src/arg_file.c, src/arg_int.c, src/arg_lit.c, src/arg_rex.c, src/arg_str.c
There is undefined behavior in how the callback functions arg_resetfn, arg_scanfn, arg_checkfn, and arg_errorfn are used currently. The original type of those functions has the parent type as `void*`, but the actual function implementations have the `void*` parent as something like `struct arg_date* parent`, but they are cast to the function type with `void*` parent. This is apparently undefined behavior, and the clang undefined behavior sanitizer catches this.
So, to see the errors, use this change to CMakeLists.txt:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 67cee27..f267a19 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -69,6 +69,9 @@ if(ARGTABLE3_ENABLE_CONAN AND EXISTS "${CMAKE_BINARY_DIR}/conanbuildinfo.cmake")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} …
```
=> Fix undefined behavior in callback functions' parameter passing

CMakeLists.txt, packaging/pkgconfig.pc.in, src/CMakeLists.txt
This pull request is based on the one (https://github.com/argtable/argtable3/pull/71) from @KOLANICH, which added the `.pc` file and CPack settings. I've improve the patch so the CPack settings can follow the best practices.
=> build: generate .pc file and supprot cpack

CMakeLists.txt
Allows build with CMake 4.0.0 without Deprecation Warning.
use the min...max syntax to allow build with newer CMake. 
ref: https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html
Fixes:
```
CMake Deprecation Warning at CMakeLists.txt:31 
(cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
```
=> build: update CMake min to min...max

.github/workflows/coverity.yml, README.md
Adding _Coverity Scan_ helps reduce risk and lower overall project cost by identifying critical quality defects and potential security vulnerabilities during development.
=> build: add coverity scan in ci

.clusterfuzzlite/Dockerfile, .clusterfuzzlite/build.sh, .clusterfuzzlite/fuzzer.c, .clusterfuzzlite/project.yaml, .github/workflows/cflite_pr.yml
This adds fuzzing by way of [ClusterFuzzLite](https://google.github.io/clusterfuzzlite/), which is a GitHub action that will perform a short amount of fuzzing for new PRs. The goal is to use fuzzing to catch bugs that may be introduced by new PRs.
If you'd like to test this the way ClusterFuzzLite runs it (by way of OSS-Fuzz) you can use the steps:
```sh
git clone https://github.com/google/oss-fuzz
git clone https://github.com/DavidKorczynski/argtable3
cd argtable3
git checkout cflite
python3 ../oss-fuzz/infra/helper.py build_fuzzers --external $PWD
python3 ../oss-fuzz/infra/helper.py run_fuzzer --external $PWD fuzzer -- -max_total_time=10
```
=> Add ClusterFuzzLite integration

.github/workflows/coverity.yml
_Coverity Scan_ allows up to 28 builds per week and 4 per day for open source projects with fewer than 100K lines of code.
To avoid exceeding this quota, the Coverity Scan workflow is now set to run only on manual trigger. This lets us run scans only when we have fixes for issues found by Coverity, preventing unnecessary builds that would waste the quota.
=> build: limit coverity scan workflow to manul trigger

.github/workflows/sonarqube.yml, src/arg_dstr.c
This patch resolves the implicit declaration warning for `vsnprintf`, which is not available in C89. A portable fallback function, `arg_vsnprintf`, is introduced. It uses `vsprintf` for C89, `_vsnprintf` for MSVC, and `vsnprintf` for C99 or later.
The implementation ensures buffers are null-terminated and output is truncated if needed, improving safety even when using `vsprintf`. With this change, the code compiles cleanly under C89 without warnings, and external functionality is unchanged.
=> fix: provide c89-compatible fallback for vsnprintf

.github/workflows/msvc.yml
This patch updates the MSVC GitHub Actions workflow to use the `strategy.matrix` feature. Instead of explicitly adding separate steps for Debug and Release builds, the workflow now builds and tests each configuration in parallel using the matrix. This simplifies the workflow and ensures both configurations are always verified.
=> build: refactor workflow to use matrix strategy for build configs

.github/workflows/mingw64.yml
This patch introduces a workflow that verifies argtable3 can be built and tested using MSYS2 MinGW64 on Windows. Both Debug and Release configurations are built and tested. The workflow ensures MinGW64 compatibility and test coverage on every change.
=> build: add ci workflow for msys2 mingw64 build and test

.github/workflows/clang.yml
This patch introduces a workflow that verifies argtable3 can be built and tested using the Clang compiler on Ubuntu. Both Debug and Release configurations are built and tested. The workflow ensures Clang compatibility and test coverage on every change.
=> build: add ci workflow for clang build and test

Makefile, tools/build
This patch revises the git tag definition and the interpretation of `version.tag` content. Git tags will now follow the SemVer standard, including optional pre-release metadata but excluding build metadata. The git commit hash will no longer be part of the git tag.
When generating `version.tag`, the git commit hash will be appended as build metadata, ensuring `version.tag` continues to adhere to the SemVer standard.
=> fix: update git tag definition and version.tag generation process

.github/workflows/asan.yml
This commit adds a GitHub Actions workflow (`asan.yml`) to detect memory issues in the `argtable3` project using AddressSanitizer (ASan). The workflow triggers on `push` and `pull_request` events targeting the `main` branch. It builds the project with ASan and runs tests to identify memory errors, including leaks and invalid accesses.
Purpose:
- Ensure memory safety by detecting issues during CI.
- Improve code quality and reliability with automated checks.
=> build: add asan memory check ci workflow

.github/workflows/valgrind.yml
This commit introduces a GitHub Actions workflow (`valgrind.yml`) to detect memory issues in the `argtable3` project using Valgrind. The workflow runs on `push` and `pull_request` events targeting the `master` branch, as well as manually via `workflow_dispatch`.
Purpose:
- Use Valgrind to identify memory leaks and invalid memory accesses.
- Automate memory issue detection during CI to improve code quality.
=> build: add valgrind ci workflow for memory issue detection

.github/workflows/sonarqube.yml
A command injection vulnerability, identified as CVE-2025-58178, was discovered in the SonarQube Scan GitHub Action versions 4 to 5.3.0. This vulnerability allows for potential execution of arbitrary commands due to untrusted input arguments being processed without proper sanitization. These arguments, when passed to the action, were treated as shell expressions, creating an exploitable pathway.
To mitigate this vulnerability, users are strongly advised to upgrade their SonarQube Scan GitHub Action to version 5.3.1 or higher. This patched version addresses the command injection issue by properly sanitizing input arguments. If a workflow uses dynamically computed arguments, it is additionally necessary to switch to using supported syntax for expressions within GitHub Actions. Workflows …
=> fix: upgrade sonarqube scan action to resolve security issue
